# NUMPY BASICS

In [1]:
import numpy as np

# We can create a NumPy ndarray object by using the array() function. To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [2]:
arr = np.array([1, 2, 3])

In [3]:
print(arr)

[1 2 3]


# Dimensions in Arrays

## Create arrays of different dimentions.

## a=A numpy array with one single integer 10

## b=A numpy array passing a list having a list= [1,2,3]

## c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

## d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [5]:
a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [6]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

# Lets print there shape as well. You can check shape using shape attribute

In [7]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(3,)
(2, 3)
(2, 2, 3)


# Lets check data type passed in our array. To check data type you can use dtype attribute

In [8]:
print(c.dtype)
print(d.dtype)

int64
int64


# Above output mean our array is having int type elements in it.

# Lets check the type of our variable. To check type of any numpy variable use type() function

In [10]:
print(type(a))
print(type(b))
print(len(b))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
3


# Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

# Create two list 11 and 12 where, 11=[10,20,30] and 12=[40,50,60] Also define two numpy arrays 13,14 where 13 has 11 as element and 14 has 12 as element

In [11]:
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)

# Lets multiply each elements of 11 with corresponding elements of 12

# Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

# Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line
# eg. %timeit my_code

In [12]:
%timeit [x * y for x, y in zip(l1, l2)]

376 ns ± 42.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

# Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array. Hence proved that numpy arrays are faster than lists.

# Fun Fact time !:

# You know in many data science interviews it is asked that what is the difference between list and array.

In [14]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


# This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [15]:
arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


In [16]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
x = np.arange(1, 17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [18]:
x = x.reshape(2, 8)
print(x)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


# As you can see above that our x changed into 2D matrix

# 2. Reshaping 1-D to 3-D array

In [19]:
x = x.reshape(2, 4, 2)
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [20]:
x = x.reshape(4, -1)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [21]:
y = x.reshape(2, 4, 2)
print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [22]:
print(y.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [23]:
a = np.arange(2, 18, 2)
print(a)

[ 2  4  6  8 10 12 14 16]


In [24]:
print(a[2])

6


In [25]:
print(a[[2, 4, 6]])

[ 6 10 14]


# Lets check the same for 2D array

In [28]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [29]:
print(a[2, 2])

9


# Well done!

# Now lets check indexing for 3 D array

In [30]:
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [31]:
print(b[0, 1, 2])

6


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
print(arr[1:5])

[2 3 4 5]


# Note: The result includes the start index, but excludes the end index

In [34]:
print(arr[5:])

[6 7 8]


In [35]:
print(arr[:5])

[1 2 3 4 5]


# STEP

# Use the step value to determine the step of the slicing
 

In [36]:
print(arr[1:7:2])

[2 4 6]


# Did you see? using step you were able to get alternate elements within specified index numbers.

In [37]:
print(arr[::2])

[1 3 5 7]


# well done!

# Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here

# Array slicing in 2-D array.

In [38]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(a[2, 1:5])

[8 9]


In [40]:
print(a[:, 2])

[3 6 9]


In [41]:
print(a[:, 1:])

[[2 3]
 [5 6]
 [8 9]]


# Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

# Numpy copy vs view

In [42]:
x1 = np.array([1, 2, 3, 4, 5])

In [43]:
x2 = x1

In [44]:
print(x1)
print(x2)


[1 2 3 4 5]
[1 2 3 4 5]


# Ok now you have seen that both of them are same

In [45]:
x2[0] = 10

In [46]:
print(x1)
print(x2)

[10  2  3  4  5]
[10  2  3  4  5]


In [47]:
print(np.shares_memory(x1, x2))

True


# Hey It's True they both share memory

# Shall we try view() function also likwise.

In [48]:
x3 = x1.view()

In [49]:
print(np.shares_memory(x1, x3))

True


# Woh! simple assignment is similar to view. That means The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [50]:
x3[0] = 100

In [51]:
print(x1)
print(x3)

[100   2   3   4   5]
[100   2   3   4   5]


# Now its proved.

# Lets see how Copy() function works

In [52]:
x4 = x1.copy()

In [53]:
x4[-1] = 900

In [54]:
print(x1)
print(x4)

[100   2   3   4   5]
[100   2   3   4 900]


# Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

# Still not convinced? Ok lets see if they both share memory or not

In [55]:
print(np.shares_memory(x1, x4))

False


# hstack vs vstack function

# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

# NumPy provides a helper function:

# 1. hstack() to stack along rows.
# 2. vstack() to stack along columns

In [56]:
print(np.hstack((x1, x4)))

[100   2   3   4   5 100   2   3   4 900]


In [57]:
print(np.vstack((x1, x4)))

[[100   2   3   4   5]
 [100   2   3   4 900]]


# We hope now you saw the difference between them.

# Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

# Lets try this function as well

In [58]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2), axis=0))

[1 2 3 4 5 6]


In [59]:
print(np.concatenate((arr1, arr2), axis=0))

[1 2 3 4 5 6]


# Adding, Insert and delete Numpy array

# You can also add 2 arrays using append() function also. This function appends values to end of array

# Lets see how

In [60]:
print(np.append(arr1, arr2))

[1 2 3 4 5 6]


# Lets use insert() function which Inserts values into array before specified index value

In [61]:
print(np.insert(x1, 4, x4))

[100   2   3   4 100   2   3   4 900   5]


# You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [62]:
x2 = np.array([1, 2, 3, 4, 5])
print(np.delete(x2, 2))

[1 2 4 5]


# Did you see? 2 value is deleted from x2 which was at index position 2

# Good Job learner!

# Thank you